### PR TITLE
Dependencies check badge

### PR DESCRIPTION
**Pull request by podviaznikov**

### CODE REVIEW

**Comment by w01fe** [comment]
Hi Anton,

Thanks for the PR.  Can you provide some context on why we want this?  There's not necessarily anything wrong if we don't bump the dependencies every time a new release of a dependency comes out (and, for example, we currently do test on Clojure 1.7, it's just in a different profile).  

Thanks,
Jason

**Comment by podviaznikov** [comment]
I personally find badges useful for two reason: 1) as a repo developer they can suggest to me that new version of my dependency is available. And maybe I should check it and see what was added - and use new feature. 2) they can provide additional hint about activity on this project (similar to last commit date, number of contributors, github stars etc). As a user it can *help* me make decision whether I should try this library or search for more actively supported alternative.

**Comment by w01fe** [comment]
Thanks for the explanation.

I can understand the sentiment, but in this case fnhouse only depends on plumbing and schema, two of our other libraries.  We do keep it roughly up to date, but I don't think it makes sense for us to bump the dependencies and do a new fnhouse release every time we do a point release of plumbing or schema, and so it's going to show as out of date a lot of the time -- which seems to send the wrong signal.  Does that make sense?  

If the badge was green only if we were a major version behind or something, then I think that would be useful for us, but otherwise I think I'm inclined to pass for now.

**Comment by podviaznikov** [comment]
@w01fe I totally understand and see how it's not suite for fnhouse. Especially because you also try to make it work with different versions of Clojure. I see now that jarkeeper doesn't support that case well.

Thanks for your feedback!

**Pull request closed without merging**
